"""Learning tests: the three API limits this server is built around, pinned to the site.

Everything this repository refuses to do rests on measurements, and a measurement decays.
These tests turn the three load-bearing ones into an alarm that goes off when
FragDenStaat changes its mind:

  1. ``POST /api/v1/message/`` refuses ``kind: "email"`` — so an e-mail reply to an
     authority cannot be created through the API at all.
  2. ``POST /anfrage/<slug>/send/message/`` ignores an OAuth bearer token completely —
     the web view is session + CSRF only, so a token is not a way around limit 1.
  3. The OpenAPI schema at ``/api/v1/schema/`` describes exactly the resources this
     server knows about — a new endpoint here may well be the reply channel we are
     missing.

**Nothing in this file creates, changes or sends anything.** Two of the tests do POST,
which is otherwise forbidden in this repository (CONTRIBUTING, ground rule 2), and both
are constructed so that a success is impossible:

  * the message POSTs carry a request URI that cannot resolve
    (``/api/v1/request/999999999/``), so the serializer is invalid and no object is
    created — the ``kind`` error we are after is reported alongside the ``request``
    error, not instead of it;
  * the web-form POST carries an empty form body, so even if the view unexpectedly
    accepted the token, there would be no message to send.

Run with ``pytest -m live``. Without a token in ``~/.config/fds-mcp/tokens.json`` the
token-bound tests skip rather than fail.
"""

from __future__ import annotations

import json
import os
import time
from pathlib import Path

import httpx
import pytest
import yaml

from fds_mcp import config
from fds_mcp.config import USER_AGENT

pytestmark = pytest.mark.live

# A request id that does not exist. Its only job is to make the serializer invalid, so
# that these POSTs can never create a message.
NONEXISTENT_REQUEST_URI = f"{config.api_url()}/request/999999999/"

# A real, public request of the maintainer's. Only the URL shape matters here: the view
# under test redirects before it ever looks at the form data.
SEND_MESSAGE_URL = (
    f"{config.base_url()}/anfrage/antrag-nach-dem-landestransparenzgesetz-rheinland-pfalz-"
    "vergabe-und-benutzung-der-schutzhuette-duengenheim/send/message/"
)

# The resources the API router exposes under /api/v1/, measured 2026-09-05. The schema is
# generated by drf-spectacular from the live router, so this set is the router. A new
# name appearing here is the interesting event — it might be the reply channel that
# POST /api/v1/message/ refuses to be.
EXPECTED_RESOURCES = frozenset({
    "articletag", "attachment", "campaign", "campaigninformationobject", "category",
    "classification", "document", "documentcollection", "documentportal", "feature",
    "following", "georegion", "governmentplan", "jurisdiction", "law", "message",
    "page", "pageannotation", "problemreport", "publicbody", "request", "schema",
    "upload", "user", "userpreference", "venue",
})

TIMEOUT = 60.0


def _real_token_path() -> Path:
    """``~/.config/fds-mcp/tokens.json`` — deliberately not ``config.tokens_path()``.

    conftest redirects ``FDS_MCP_HOME`` into a tmp directory for every test. That is
    right everywhere else and wrong here: these tests need the operator's actual token,
    because the endpoints under test answer 401 without one and the measurement would
    then say nothing.
    """
    xdg = os.environ.get("XDG_CONFIG_HOME")
    root = Path(xdg).expanduser() if xdg else Path.home() / ".config"
    return root / "fds-mcp" / "tokens.json"


@pytest.fixture
def token() -> str:
    path = _real_token_path()
    if not path.exists():
        pytest.skip(f"no OAuth token at {path} — run 'fds-mcp login'")
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:  # pragma: no cover - corrupt token file
        pytest.skip(f"{path} is unreadable: {exc}")
    access = data.get("access_token")
    if not access:
        pytest.skip(f"{path} holds no access_token — run 'fds-mcp login'")
    if float(data.get("expires_at") or 0) <= time.time():
        pytest.skip("access token expired — run 'fds-mcp status' to refresh it")
    return str(access)


def _headers(token: str | None = None) -> dict[str, str]:
    headers = {"User-Agent": USER_AGENT, "Accept": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def _post_message(token: str, kind: str) -> httpx.Response:
    """POST /api/v1/message/ with a deliberately unresolvable request URI."""
    return httpx.post(
        f"{config.api_url()}/message/",
        json={"request": NONEXISTENT_REQUEST_URI, "kind": kind},
        headers=_headers(token),
        timeout=TIMEOUT,
    )


def _skip_on_auth_failure(response: httpx.Response) -> None:
    if response.status_code in (401, 403):
        pytest.skip(
            f"HTTP {response.status_code} from {response.request.url} — the stored token "
            "is not accepted, so nothing was measured. Run 'fds-mcp login'."
        )


# ==========================================================================
# 1. the API refuses to create e-mail messages
# ==========================================================================

def test_email_kind_is_rejected_by_the_api(token):
    """``kind: "email"`` is refused by the serializer, not merely undocumented.

    froide's ``OnlyPostalMessagesWritable`` is what produces the ``kind`` error. If this
    test starts failing because the key is gone, the API has grown the ability to write
    e-mail messages and `build_reply_draft`'s reason for existing has changed.
    """
    response = _post_message(token, "email")
    _skip_on_auth_failure(response)
    assert response.status_code == 400, response.text
    body = response.json()
    assert "kind" in body, (
        f"POST /message/ with kind='email' no longer reports a 'kind' error: {body}"
    )
    # The invalid request URI is reported too. That is the proof that the serializer ran
    # and rejected the payload as a whole — no message object can have been created.
    assert "request" in body, body


def test_post_kind_is_accepted_negative_control(token):
    """The calibration. Without it the test above is worthless.

    A 400 carrying a ``kind`` key could equally well come from the unresolvable request
    URI, from the endpoint rejecting every POST, or from the token lacking a scope. This
    is the identical call with exactly one field changed: ``kind: "post"``. It must
    still be a 400 — the request URI is still invalid — but it must NOT carry a ``kind``
    error. That difference is the whole measurement.
    """
    response = _post_message(token, "post")
    _skip_on_auth_failure(response)
    assert response.status_code == 400, response.text
    body = response.json()
    assert "kind" not in body, (
        f"kind='post' is now refused as well: {body}. Either the write path closed "
        "entirely, or the 'kind' error in the sibling test no longer means what it did."
    )
    assert "request" in body, body


# ==========================================================================
# 2. the web view ignores bearer tokens
# ==========================================================================

@pytest.mark.parametrize("authenticated", [True, False], ids=["with-token", "no-token"])
def test_web_send_message_view_ignores_bearer_tokens(token, authenticated):
    """``/anfrage/<slug>/send/message/`` answers 302 to the login page either way.

    The Django view is session + CSRF authenticated; OAuth is an API-only scheme on
    fragdenstaat.de. Both responses being byte-identical in status and Location is what
    rules out "the token works, we just posted the form wrong".

    The form body is empty on purpose. Should this view ever start honouring bearer
    tokens, an empty POST is the one payload that still cannot send anything.
    """
    response = httpx.post(
        SEND_MESSAGE_URL,
        data={},
        headers=_headers(token if authenticated else None),
        timeout=TIMEOUT,
        follow_redirects=False,
    )
    assert response.status_code == 302, (
        f"expected a redirect to the login page, got HTTP {response.status_code}. "
        "If this is a 403 the view now sees the token and refuses on CSRF; if it is a "
        "2xx the view accepted an authenticated POST and build_reply_draft's premise is "
        "gone."
    )
    location = response.headers.get("location", "")
    assert location.startswith("/account/login/"), location


# ==========================================================================
# 3. the schema describes the router we think it does
# ==========================================================================

def test_schema_resources_match_registered_routers():
    """No token needed — the schema is public.

    drf-spectacular generates it from the live router, so the set of first path segments
    under ``/api/v1/`` is the set of registered resources. There is no documentation
    delta to allow for.
    """
    response = httpx.get(
        f"{config.api_url()}/schema/",
        headers={"User-Agent": USER_AGENT,
                 "Accept": "application/vnd.oai.openapi+json, application/json"},
        timeout=TIMEOUT,
        follow_redirects=True,
    )
    assert response.status_code == 200, response.text[:500]
    try:
        schema = response.json()
    except ValueError:  # the endpoint also serves YAML
        schema = yaml.safe_load(response.text)

    resources = {path.split("/")[3] for path in schema["paths"]
                 if path.startswith("/api/v1/") and len(path.split("/")) > 3}
    assert resources == set(EXPECTED_RESOURCES), {
        "new": sorted(resources - EXPECTED_RESOURCES),
        "gone": sorted(EXPECTED_RESOURCES - resources),
    }


def test_schema_message_endpoint_still_has_no_email_path():
    """A second reading of the same schema: no resource offers an e-mail reply.

    Guards the gap from the other side. ``/api/v1/message/`` exists and accepts POST —
    the restriction lives in the serializer, not in the router — so the router alone
    cannot tell us the channel is closed. What it can tell us is that no *other*
    resource has appeared to open one.
    """
    response = httpx.get(
        f"{config.api_url()}/schema/",
        headers={"User-Agent": USER_AGENT,
                 "Accept": "application/vnd.oai.openapi+json, application/json"},
        timeout=TIMEOUT,
        follow_redirects=True,
    )
    assert response.status_code == 200
    try:
        schema = response.json()
    except ValueError:
        schema = yaml.safe_load(response.text)

    assert "/api/v1/message/" in schema["paths"]
    assert "post" in schema["paths"]["/api/v1/message/"]
    reply_paths = [p for p in schema["paths"]
                   if any(word in p for word in ("reply", "send", "email"))]
    assert reply_paths == [], reply_paths
